spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:petstore_db;MODE=PostgreSQL;
    username: sa
    password:
  jpa:
    properties:
      hibernate.default_schema:
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    schemas:
