springfoxdocumentation:
  swagger:
    v2:
      path: /api-docs
      
server:
  port: ${PETSTOREORDERSERVICE_SERVER_PORT:8080}

petstore:
  service:
    product:
      url: ${PETSTOREPRODUCTSERVICE_URL:http://localhost:8082}
    order-items-reserver:
      url: ${PETSTORE_ORDER_ITEMS_RESERVER_URL:http://localhost:7071}

spring:
  application:
    name: petstoreorderservice
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    azure:
      cosmos:
        enabled: true
        endpoint: https://petstore-account.documents.azure.com:443/
        key: ${COSMOS_DB_KEY}
        database: petstore_db

management:
  endpoints:
    web:
      exposure:
        include: "*"       
  trace:
    http:
      enabled: true 
  endpoint:
    httptrace:
      enabled: true
