spring:
  cloud:
    azure:
      cosmos:
        enabled: ${ENABLE_COSMOS_DB_EMULATOR:true}
        endpoint: https://localhost:8084
        key: C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
        database: petstore_db
